### ISSUE TITLE
Distortion model for fisheye cameras

### ISSUE THREAD

**Issue by youngguncho** [berndpfrommer/tagslam#14]
Hello.
I try to use TagSLAM with intel t265 (stereo fisheye cameras).
For tagslam, the distortion model for fisheye camera is equidistant. However, the recommanded distortion model in Kalibr is radtan (since omni-radtan is the recommended model for fisheye camera).
What is your recommendation for using camera parameters for tagslam with fisyeye cameras? Which calibration model did you use for fisheye camera with Kalibr?
Thank you.

**Comment by berndpfrommer** [comment]
From all I can tell, the Intel t265 has a conventional fisheye lens, which means you should use an equidistant "distortion" model, both in Kalibr, and in TagSLAM.
Note that the word "distortion" is somewhat misleading. The better way to say this is that the lens has an equidistant projection function:

https://en.wikipedia.org/wiki/Fisheye_lens

Where did you see the recommendation to use "omni-radtan" for Kalibr with fisheye lenses? Just curious.

I suggest you use Kalibr in equidistant mode and see what you get. I had some cases where it couldn't do the intrinsic calibration, but if it does converge, it should give you the right numbers. Have a careful look at the diagnostic pdf file that Kalibr produces. Reprojection error graph should show about 1 pixel or so error. I have calibrated about a dozen different fisheye lenses, and they all come out with very low distortion coefficients, rarely more than 0.01. So if you get small numbers, equidistant is definitely right. Note that the distortion coefficients really measure distortion, i.e. the extent to which your lens *does not* follow the equidistant projection model.
In case Kalibr bombs out you can try your luck with this package:
https://github.com/KumarRobotics/multicam_calibration
It is not as simple to use as Kalibr, can't do IMU calibration etc, but it doesn't bomb out on the intrinsics, and is substantially faster than Kalibr (that's the reason we wrote this package). Anyways, first try Kalibr.
