### ISSUE TITLE
gtsam build problem

### ISSUE THREAD

**Issue by m4xr1sk** [berndpfrommer/tagslam#16]
During the build process, on a Raspberry PI 4 I have this error:

```
/home/pi/catkin_ws/src/tagslam/src/gtsam_optimizer.cpp: In member function ‘virtual tagslam::FactorKey tagslam::GTSAMOptimizer::addDistanceMeasurement(double, double, Eigen::Vector3d, tagslam::ValueKey, tagslam::ValueKey, Eigen::Vector3d, tagslam::ValueKey, tagslam::ValueKey)’:
/home/pi/catkin_ws/src/tagslam/src/gtsam_optimizer.cpp:173:14: error: ‘transform_from’ is not a member of ‘gtsam’
       gtsam::transform_from(T_w_b_1, gtsam::transform_from(T_b_o_1, X_o_1));
```

Do you have any suggestion?

**Comment by berndpfrommer** [comment]
I assume you have compiled your own version of GTSAM. You may need a different version. Try compiling GTSAM from the exact same commit that I was working off of, as described in this discussion:

https://groups.google.com/forum/#!searchin/tagslam/tx2%7Csort:date/tagslam/rO6MBDXsV7I/sRo2eEORAAAJ
