### ISSUE TITLE
Camera pose, rotation conventions

### ISSUE THREAD

**Issue by matheusbg8** [berndpfrommer/tagslam#18]
Hi Bernd,

I am testing your code and I am having issues defining the camera poses, more specifically the rotation. Since the ROS rotations are usually defined as quaternions, rotation matrix, or Euler RPY, my first attempt was to define the camera rotation vector as Euler RPY (XYZ). However, it doesn`t seem the right representation.

After reading your code I found the following:

https://github.com/berndpfrommer/tagslam/blob/f46153a1a907680e718d2300d1df90d3d062ff0a/src/geometry.cpp#L17-L34

The answer is in the code, the length of the rotation vector is the angle in radians, and its direction represent the rotation axis. I could not find references in your documentation https://berndpfrommer.github.io/tagslam_web/input_files/ about it. Is there an easy way to convert RPY or Quaternion to your representation? I ask because if you use tf_echo you will get this kind of representation (as you can see [here](http://wiki.ros.org/tf#tf_echo)).

Can I use https://www.andre-gaschler.com/rotationconverter/ to convert RPY to "Axis with angle magnitude (radians) [x, y, z]" ? 

Thanks!

**Comment by berndpfrommer** [comment]
Sorry for the late reply!
Yes, you are right, the documentation is lacking. Please leave this issue open until I get around to documenting that the rotation is specified in axis * angle notation, i.e. vee(log(R)).

**Comment by berndpfrommer** [comment]
Thanks again for pointing this out!
Fixed with commit 6cbe70d69add6153abb565ffc65ea660fb76aecb of the tagslam_web repo.
