### ISSUE TITLE
can not get tagslam pose

### ISSUE THREAD

**Issue by zzl20** [berndpfrommer/tagslam#19]
Hi, i used my owndata(rosbag) to run tagslam,  "the subgraph err :" always cout "0", and can not publish odomtry! Is there anything wrong ?  It is very confused !!!

**Comment by berndpfrommer** [comment]
Can you please provide more information to go by? The beginning of the tagslam console output, your tagslam launch files, your tagslam.yaml, cameras.yaml, camera_poses.yaml, maybe a ``rosbag info <name_of_rosbag>``?

**Comment by zzl20** [comment]
> Can you please provide more information to go by? The beginning of the tagslam console output, your tagslam launch files, your tagslam.yaml, cameras.yaml, camera_poses.yaml, maybe a `rosbag info <name_of_rosbag>`?



The rosbag info is:
![rosbag_info](https://user-images.githubusercontent.com/26411422/94093820-b40fe200-fe50-11ea-85ec-4483b8000297.png)
The tagslam launch file is :
![launch](https://user-images.githubusercontent.com/26411422/94093874-d73a9180-fe50-11ea-8822-80c2f7b9e9e3.png)
The cameras.yaml is :
![camera_yaml](https://user-images.githubusercontent.com/26411422/94093918-eb7e8e80-fe50-11ea-8b13-f8cb106cb064.png)
The camera_poses.yaml and the tagslam.yaml is same as example file.


The output is :
![output1](https://user-images.githubusercontent.com/26411422/94094042-27b1ef00-fe51-11ea-8bc2-86eca26dd6b6.png)
![output2](https://user-images.githubusercontent.com/26411422/94094054-2bde0c80-fe51-11ea-9cc3-1d02502aa6a5.png)
![output3](https://user-images.githubusercontent.com/26411422/94094064-300a2a00-fe51-11ea-84b3-72c11aa1a35d.png)

i want get camera pose, but it is not optimize and can not publish odomtry!

**Comment by zzl20** [comment]
> Can you please provide more information to go by? The beginning of the tagslam console output, your tagslam launch files, your tagslam.yaml, cameras.yaml, camera_poses.yaml, maybe a `rosbag info <name_of_rosbag>`?

hi , i have find the problem, thank you very much
