### ISSUE TITLE
Why not support quaternions

### ISSUE THREAD

**Issue by zthcool** [berndpfrommer/tagslam#24]
when set "amnesia" to true, the tags position should be known in advance. Does it only support rotation? not surpport oriention?.I need transform the oriention to rotation firstly.And there will be mistaken when the rotation transform back to orientation in RVIZ.

**Comment by berndpfrommer** [comment]
The first sentence I understand, and it it is correct.
About the second one: can you explain the difference between rotation and orientation? An orientation can be specified in many ways, including: a rotation matrix, a quaternion, or a rotation vector. TagSLAM uses rotation vectors, which are the vector obtained by applying the "v" operator to omega = log(R), where R is the rotation matrix. This representation is called "axis with angle magnitude". Here is a web site that converts between the various representations:
https://www.andre-gaschler.com/rotationconverter/
