### ISSUE TITLE
Question: What if a frame lacks markers?

### ISSUE THREAD

**Issue by soulslicer** [berndpfrommer/tagslam#25]
Is there an example to demonstrate a case where a couple of frames lacks markers and one needs to use some VO or IMU data for forward state estimation?

**Comment by berndpfrommer** [comment]
Here is an example where sometimes hundreds of frames do not have markers. Odom was provided by msckf-vio.

https://github.com/berndpfrommer/tagslam_test/tree/master/tests/test_12
