### ISSUE TITLE
Is here a bug after removing vertex and adding factor to graph, but don't add factor to optimizer?

### ISSUE THREAD

**Issue by hjxwhy** [berndpfrommer/tagslam#27]
https://github.com/berndpfrommer/tagslam/blob/c0c5c76aeb169be1779b405a99604f57a1471f82/src/graph_utils.cpp#L124

Hi, I have read your code carefully, and I found here when you filtered the vertex that doesn't be optimized you just add the factor to the graph and doesn't add those factor to the optimizer. Is it right?

**Comment by berndpfrommer** [comment]
I frankly no longer remember how this logic works. I just remember it's very tricky. Is there a particular case that is broken that you want to fix? It's easier to look at a concrete case.
You are wondering why it is not adding the factor to the optimizer? I'm more puzzled why it is adding the value to the optimizer.

**Comment by hjxwhy** [comment]
Yes, I am wondering why it is not adding the factor to the optimizer. The pose values are added to the GTSAM's new value but the factors aren't added to the GTSAM's graph. It is a corner case I have tested many times and the function https://github.com/berndpfrommer/tagslam/blob/c0c5c76aeb169be1779b405a99604f57a1471f82/src/graph_utils.cpp#L89 has no effect.

**Comment by slmMuc2fly** [comment]
Slam anytime

**Comment by berndpfrommer** [comment]
closing this as will-not-fix
