### ISSUE TITLE
Localization with imu data 

### ISSUE THREAD

**Issue by antithing** [berndpfrommer/tagslam#31]
Hi, and thank you for sharing this code.
Is there any examples of pre-mapped markers,  and a camera (D455) performing localization using frames and imu data?

Thanks

**Comment by berndpfrommer** [comment]
This is not possible directly. You would first have to feed the real sense images and IMU data into a VIO package such as eg.  https://github.com/KumarRobotics/msckf_vio
Then you can feed the odometry output into Tagslam. You could do this in real time if necessary, although Tagslam can only run in real time if the tags are mapped beforehand.

**Comment by antithing** [comment]
Understood, thank you.
